---
- name: Update, Install, and Configure Floating License Server
  hosts: FLS
  become: true
  
  vars_files:
    - vars.yml
    
  tasks:
  - name: Set Hostname to FQDN
    hostname: 
      name: "{{ fqdn }}"
      use: systemd

  - name: Update CentOS 8
    yum:
      name: "*"
      state: latest

  - name: Install chrony
    yum:
      name: chrony
      state: present

  # Needed for unzipping Jetbrains FLS file
  - name: Install Unzip
    yum:
      name: unzip
      state: present

  - name: Make sure chronyd is started now and at boot.
    service:
      name: chronyd
      state: started
      enabled: true

  - name: Install Java 8
    yum:
      name: java-1.8.0-openjdk-devel
      state: present

  - name: Create directory for FLS
    file:
      path: "{{ jetbrains_dir }}"
      state: directory

  - name: Download Jetbrains FLS Zip file
    get_url:
      url: "https://download.jetbrains.com/lcsrv/license-server-installer.zip"
      dest: "/tmp"

  - name: Unzip Jetbrains FLS Zip file
    unarchive:
      src: "/tmp/license-server-installer.zip"
      dest: "{{ jetbrains_dir }}"
      remote_src: true
      creates: "{{ jetbrains_dir }}/bin/license-server.sh" 

  - name: Copy FLS Service Daemon File 
    copy:
      src: files/fls.service
      dest: /etc/systemd/system
      mode: 0755

  - name: Start and Enable FLS Service
    service:
      name: fls.service
      state: started
      enabled: true
      daemon_reload: true